### ISSUE TITLE
Failed to load dynamic library 'libc.so.6': 126

### ISSUE THREAD

**Issue by muxab** [canonical/desktop_notifications.dart#26]
when testing the pack for windows and android ,, 

[ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'libc.so.6': 126
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:55)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:20:12)
#2      getuid
package:dbus/src/getuid_linux.dart:8
#3      new DBusClient.session
package:dbus/src/dbus_client.dart:223
#4      new NotificationsClient
package:desktop_notifications/src/notifications_client.dart:233
#5      main
package:notifications_one/main.dart:4
#6      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:142:25)
#7      _rootRun (dart:async/zone.dart:1354:13)
#8      _CustomZone.run (dart:async/zone.dart:1258:19)
#9      _runZoned (dart:async/zone.dart:1789:10)
#10     runZonedGuarded (dart:async/zone.dart:1777:12)
#11     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:138:5)
#12     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
#13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
Unable to parse JSON message:
The document is empty.

**Comment by robert-ancell** [comment]
This is [fixed in dbus.dart](https://github.com/canonical/dbus.dart/issues/255).
