### ISSUE TITLE
Use http path for icons

### ISSUE THREAD

**Issue by krille-chan** [canonical/desktop_notifications.dart#4]
Hey, thank you very much for this awesome package. I'm currently integrating it in my app FluffyChat. Is there a way to use web urls like `https://your-domain/image.png` as `appIcon` or a recommended way to implement this?

**Comment by robert-ancell** [comment]
So sorry, for some reason I wasn't notified of this issue :(

The notifications spec doesn't allow sending URLs like this, but instead you can download the icon yourself and then use `NotificationHint.imageData` to send the data to the notifications server. There is a basic example in `examples/hints.dart` that shows a simple case.

Hope this helps!
